### ISSUE TITLE
work with staticfiles

### ISSUE THREAD

**Issue by yarbelk** [django-admin-tools/django-admin-tools#2]
When using something like Django-storages, django-compressor or related, esp when uploading to s3 or a CDN, the media_url() manual creation of asset URIs breaks down.

This can be fixed by leveraging the staticfiles app, and replacing the/extending the static template insteand of rolling one based on the media_url()

**Comment by andybak** [comment]
I'm guessing that's left over from earlier support for Django < 1.3 but you're right and it should be fairly simple to fix. As always - patches welcome. :)

**Comment by izimobil** [comment]
This could be done as part of bug #3 , but I second @andybak , pull requests are welcome !

**Comment by izimobil** [comment]
Should be fixed now.
