### ISSUE TITLE
conflict with django.apps.AppConfig

### ISSUE THREAD

**Issue by eternalfame** [django-admin-tools/django-admin-tools#23]
In new django versions there's ability to create AppConfig classes where developer can provide a verbose name for an application and much more.
But when I use this AppConfig class, the application page (e.g. /admin/app_name/) gives an unfiltered list of all models from all applications ignoring their app_labels.
The issue disappears when I disable admin_tools and use standard django admin panel

**Comment by eternalfame** [comment]
I rewrote dashboard.utils.get_app_index_dashboard function so it works, but not sure it will not provide further issues

**Comment by izimobil** [comment]
Could you be more precise about the issue and publish the changes you made ? thanks.

**Comment by eternalfame** [comment]
okay,
when application verbose name is translated, the index dashboard of this app (e.g. /admin/<app_name>/) returns the list of all models registered on this site, not the models that belong to the app (as it should be)
example: django.contrib.auth app translated in russian:
before fix:
![1 before fix](https://cloud.githubusercontent.com/assets/3793809/10755716/ba8556b4-7ce2-11e5-96d6-5394290006fc.png)
after:
![2 after](https://cloud.githubusercontent.com/assets/3793809/10755715/ba82b77e-7ce2-11e5-9b8e-ddfd81563df5.png)
