### ISSUE TITLE
django.conf.urls.patterns() is deprecated and will be removed in Django 1.10

### ISSUE THREAD

**Issue by benjamindej** [django-admin-tools/django-admin-tools#24]
Deprecated 'django.conf.urls.patterns' are still used at some places.

`(...)admin_tools/urls.py:10: RemovedInDjango110 Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.`

Run
`$ python -Wall manage.py test`
 to see the other warnings.

**Comment by izimobil** [comment]
Fixed in https://github.com/django-admin-tools/django-admin-tools/commit/9ab2333fe4cdff5a92f657593157f5ffd26c41e8
