### ISSUE TITLE
Django flat theme support

### ISSUE THREAD

**Issue by izimobil** [django-admin-tools/django-admin-tools#25]
To support django-flat-theme for django 1.9 and django < 1.9 with django-flat-theme as an external app, we need:
- a "detect_admin_theme" helper that would return "legacy" or "flat" based on django version or 'flat' in installed_apps
- additional css files (and maybe sprite image) for the flat theme, that will override necessary css classes of the default files (untouched)
- modify template tags and templates to include (or not) the new css files

**Comment by vdboor** [comment]
Addition: when implementing this, one may want to look at https://github.com/vdboor/django-admin-tools/tree/flat-theme for inspiration where I've implemented CSS changes to make the theme appear more in line with flat-theme. These changes are not backwards compatible.

**Comment by izimobil** [comment]
@andybak , @vdboor 

Pull https://github.com/django-admin-tools/django-admin-tools/pull/26 request should fix the issue.

DAT now looks good with or without the flat theme changes in django 1.9, tested on django 1.7, 1.8 and 1.9 (note that I didn't test dj17 or dj18 with django-flat-theme as a separate app).
