### ISSUE TITLE
0.6.0 distrs from pypi are broken

### ISSUE THREAD

**Issue by kilgoretrout1985** [django-admin-tools/django-admin-tools#28]
Hello,

django-admin-tools-0.6.0.tar.gz and django_admin_tools-0.6.0-py2.py3-none-any.whl from https://pypi.python.org/pypi/django-admin-tools are broken - they both don't have admin_tools/template_loaders.py file. 

So official docs, requiring to setup 'admin_tools.template_loaders.Loader' + 0.6.0 installed with pip = ImportError.

**Comment by izimobil** [comment]
Files are not broken at all, 'admin_tools.template_loaders.Loader' was introduced **after** the 0.6.0 release and the relevant docs for this version are correct: http://django-admin-tools.readthedocs.org/en/v0.6.0/

The "latest" docs refer to the next (in development) version of django-admin-tools that is not released yet.
