### ISSUE TITLE
Update and cleanup django-admin-tools code to reflect compatibility with django >= 1.7 

### ISSUE THREAD

**Issue by izimobil** [django-admin-tools/django-admin-tools#3]
Remove old migrations and adopt new migration system.
Remove all hacks that try to make it compatible with django <= 1.6.
Update docs/setup/etc.

**Comment by andybak** [comment]
Migrations should be OK. I've left south_migrations in place. We probably want to document how to get updated from earlier versions. 

(I'm still in the process of figuring out the best way to do this for my own projects some of which are still on 1.4. Currently I'm updating to Django 1.6, running all south migrations and then updating all code to 1.7+ and running native Django migrations)

**Comment by andybak** [comment]
Switched the test runner to DiscoverRunner - @kmike - is it safe to delete runtests.sh now?

**Comment by izimobil** [comment]
I think it's safe, but docs need to be updated, especially https://github.com/django-admin-tools/django-admin-tools/blob/master/docs/testing.rst

**Comment by kmike** [comment]
@izimobil said it all.

**Comment by izimobil** [comment]
Should be completely fixed now.
