### ISSUE TITLE
django.db.migrations.loader.BadMigrationError: Migrated app 'menu' contains South migrations. 

### ISSUE THREAD

**Issue by madEng84** [django-admin-tools/django-admin-tools#31]
1. django.db.migrations.loader.BadMigrationError: Migrated app 'menu' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.

2. django.db.migrations.loader.BadMigrationError: Migrated app 'dashboard' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.

The solution is renaming the *migrations* package in *south_migrations* 

At the moment I have fixed it indicating an other 'migrations' package for them putting this code in my settings.py:

SOUTH_MIGRATION_MODULES = {
    'cms': 'cms.migrations',
    ...
    
    #FIX BAD MIGRATION ERRORS THROUGH TEMPORARY WORKAROUND
    'menu': 'cms.migrations',
    'dashboard': 'cms.migrations',
    'django_extensions': 'cms.migrations',
    'filer': 'cms.migrations',

  ...
}

The same problem for django_extensions, but it has been resolved but not pushed to pypi(as you can read [here](https://github.com/django-extensions/django-extensions/issues/760) ), and for django_filer (as you can read [here](https://github.com/stefanfoulis/django-filer/issues/603) )

**Comment by izimobil** [comment]
What version are you using ? Migrations have already been renamed since version 0.6.0...
See https://github.com/django-admin-tools/django-admin-tools/commit/8b144dddf027f72c98713fabe5e9e0eba58e7c2d .

**Comment by madEng84** [comment]
@izimobil you are right.
I'm using version 0.5.2 because of a conflict with an other package, but actually i don't remember what package... I think modeltranslation or/and easy_thumbnails.
I found this error using 0.5.3
