### ISSUE TITLE
Error on windows envirament

### ISSUE THREAD

**Issue by soulraven** [django-admin-tools/django-admin-tools#32]
i get this error on windows environment:
[Errno 22] Invalid argument: u'G:\\Developer\\PyCharmProjects\\proGeekEnv\\lib\\site-packages\\admin_tools\\theming\\templates\\admin:admin\\index.html'

http://dpaste.com/0JYS2RA

**Comment by izimobil** [comment]
Have you added the new required template loader (admin_tools.template_loaders.Loader) to your TEMPLATES settings variable ? see http://django-admin-tools.readthedocs.org/en/latest/quickstart.html#basic-configuration

**Comment by soulraven** [comment]
yes, is added, the problem appears only when i have ported to windows machine, on linux is working just fine
```TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, "static", "templates"), ],
		# 'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				"django.core.context_processors.media",
				'django.core.context_processors.i18n',
				"bootstrap_theme.context_processors.system_message",
				"djcopyright.context_processors.djcopyright_years",
				"dashboard_main.context_processors.system_message",
				"dashboard_main.context_processors.settings_export"
			],
			'loaders': (
				# 'django.template.loaders.filesystem.load_template_source',
				# 'django.template.loaders.app_directories.load_template_source',
				'django.template.loaders.app_directories.Loader',
				'django.template.loaders.filesystem.Loader',
				'admin_tools.template_loaders.Loader'
			),

		},

	},
]

**Comment by andybak** [comment]
dpaste link has expired. probably best to put a trimmed traceback directly into the issue itself. Can you do that?

**Comment by izimobil** [comment]
I think this error is caused by a django template loader located before admin_tools loader... On windows AFAIK semicolon is not accepted in filenames, hence the Errno 22.

I think that a quick fix would be to put the 'admin_tools.template_loaders.Loader' **first** in the template loaders list.

@soulraven can you try this and tell us if it solves the issue ?

**Comment by izimobil** [comment]
@soulraven I'd like to update the documentation if what I suggested is true and I don't have a Windows environment to test, so it would be great if you could take some time to verify this. Thanks.

**Comment by soulraven** [comment]
yes, is true, i have try the solution and is working.
