### ISSUE TITLE
DjangoUnicodeDecodeError when model title contains non-ascii characters

### ISSUE THREAD

**Issue by mjl** [django-admin-tools/django-admin-tools#33]
Our models.py contains

```python
class Entry(models.Model):
    class Meta:
        verbose_name_plural = 'Einträge'
```

This causes django-admin-tools 0.7.0 to explode with

```
DjangoUnicodeDecodeError at /admin/
'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128). 
You passed in <django.utils.functional.__proxy__ object at 0x106a53310> (<class 'django.utils.functional.__proxy__'>)
```

The cause are the `{% trans item.title|capfirst %}` in *admin_tools/menu/templates/admin_tools/menu/item.html* and *admin_tools/dashboard/templates/admin_tools/dashboard/modules/app_list.html*.

For one, I'm not sure that doing a capfirst and then translating ist the right thing in the first place: the translations should be coming from the app in question and modifying the lookup strings first with `capfirst` will break any intentional translation.

But the real problem is the actual translation. Trying to translate those model titles looks wrong, since if I wanted to translate, the right place to do that is in the model's Meta `verbose_name`/`verbose_name_plural`. Throwing a munged model's name into the translating engine and hoping for the best will probably not work right most of the time.

The attached patch removes the `{% trans %}` blocks in favour of the original strings and allows things to continue.

[no_translation_patch.txt](https://github.com/django-admin-tools/django-admin-tools/files/35445/no_translation_patch.txt)

**Comment by izimobil** [comment]
I agree with you on the trans call, it should not be the responsability of admin_tools to do this, we will look at this soon (there are a lot of unecessary trans calls IMO).

Capfirst is more justified because django models (like auth.Group) are not capitalized and it look weird when mixed with capitalized models.

That said, I think your original error is due to the fact that your verbose_name_plural is a string instead of a unicode instance.

**Comment by vstoykov** [comment]
@mji I think that @izimobil  is right. Looks like your `verbose_name` is not a `unicode` instance. But for all to be sure if this is the reason can you tell us which version of python you are using (python 2 or 3) and if you are on 2 do you have `from __future__ import unicode_literals` on top of the file?
