### ISSUE TITLE
incompatible with django.template.loaders.cached.Loader

### ISSUE THREAD

**Issue by puterleat** [django-admin-tools/django-admin-tools#34]
Currently admin-tools raises an exception if you use django.template.loaders.cached.Loader, which is quite useful with floppyforms to improve performance

This line is responsible: https://github.com/django-admin-tools/django-admin-tools/blob/master/admin_tools/__init__.py#L46  because cached.Loader makes TEMPLATE_LOADERS into a nested list: https://docs.djangoproject.com/en/dev/ref/templates/api/#django.template.loaders.cached.Loader

Perhaps the check could be nested into subitems of TEMPLATE_LOADERS if the item is not isinstance(basestring)?

**Comment by izimobil** [comment]
Thanks for the bug report, be7ce4e should fix the issue.
