### ISSUE TITLE
Template loader

### ISSUE THREAD

**Issue by sergei-maertens** [django-admin-tools/django-admin-tools#35]
I just tried updating to 0.7.0 which requires ``admin_tools.template_loaders.Loader`` to be added to the ``TEMPLATES`` setting. However, I think the ``check_config`` behaviour is incorrect, as template loaders can be nested.

See https://github.com/modelbrouwers/modelbrouwers/blob/c1d3e7ec6976fda11f5f00d4ba923a6a506b82d6/src/conf/settings/base.py#L139 and https://github.com/modelbrouwers/modelbrouwers/blob/c1d3e7ec6976fda11f5f00d4ba923a6a506b82d6/src/conf/settings/production.py#L72 for the used configuration.

In development (without the cached template loader) everything is fine.

**Comment by izimobil** [comment]
This issue has been fixed by https://github.com/django-admin-tools/django-admin-tools/commit/be7ce4e77a68d7f3986dbd7fa8ba38dddf0c59a5 recently. A new bugfix release is coming soon.

**Comment by sergei-maertens** [comment]
Great, thank you. I was in a bit of a hurry and didn't check the closed issues, I'm sorry!

**Comment by izimobil** [comment]
No problem, BTW the 0.7.1 release is published.
