### ISSUE TITLE
check_configuration assumes parameters to loaders are always tuples

### ISSUE THREAD

**Issue by spookylukey** [django-admin-tools/django-admin-tools#37]
Specifically:

https://github.com/django-admin-tools/django-admin-tools/blob/master/admin_tools/__init__.py#L38

    for loader in loaders:
        if isinstance(loader, (tuple, list)):
            loaders += loader[1]

This code is presumably trying to handle:

    TEMPLATE_LOADERS = (
        ('django.template.loaders.cached.Loader', (
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        )),
    )

It has multiple issues:

1) It mutates settings.TEMPLATE_LOADERS - it should leave it alone.
2) It only handles 'django.template.loaders.cached.Loader', assuming that the parameter must be a tuple/list. It doesn't handle other  TEMPLATE_LOADERS which might take different parameters altogether.
3) It assumes that it TEMPLATE_LOADERS is a tuple, when it could be a list.

Better code would be something like:

    loaders = list(loaders)  # our copy
    for loader in loaders:
        if isinstance(loader, (tuple, list)):
            if len(loader) > 1:
                arg = loader[1]
                if isinstance(args, tuple):
                    # possibly CachedLoader parameters, which are themselves loaders.
                   loaders.extend(arg)

(untested)

4) It raises a hard error if the configuration is "incorrect". For my use case, I need to do something a bit different, which means that `"admin_tools.template_loaders.Loader"` is never in my `TEMPLATE_LOADERS` (we have a custom cached loader into which we can include the admin_tools loader, but not using the same parameter mechanism that the stock cached loader uses).

Instead of raising an `IncorrectlyConfigured`, this should be using the checks framework - https://docs.djangoproject.com/en/1.7/topics/checks/

**Comment by izimobil** [comment]
@spookylukey thanks, https://github.com/django-admin-tools/django-admin-tools/commit/9f3ba54d34a77592a33fa47ce8439df1efa7b9c1 should fix all issues

**Comment by spookylukey** [comment]
Thanks so much!
