### ISSUE TITLE
TemplateDoesNotExist at /admin/ admin:admin/index.html error

### ISSUE THREAD

**Issue by sztankatt** [django-admin-tools/django-admin-tools#42]
Just installed this package, and I get the above error.

Seems that I cannot use `{% extends "admin:admin/index.html" %}` within the templates.

Any thoughts?

**Comment by Anton-Shutik** [comment]
@sztankatt Got exactly the same issue when upgrading  Django from 1.8.7 to 1.9.1

**Comment by sztankatt** [comment]
@Anton-Shutik Yeah, although I have Django 1.8.5. Also, to clarify, I am running it on ubuntu 14.04 locally.

**Comment by izimobil** [comment]
But have you correctly configured django-admin-tools ?

Since versions 0.7.x, you must add `admin_tools.template_loaders.Loader` to your template loaders as stated in the [release notes](https://github.com/django-admin-tools/django-admin-tools/blob/master/CHANGELOG) and in the [documentation](http://django-admin-tools.readthedocs.org/en/latest/quickstart.html#basic-configuration).

**Comment by Anton-Shutik** [comment]
@izimobil 
That helped for me!

Thanks!

**Comment by botnetbuster** [comment]
I'm having the same problem with Django 1.7 but followed the documentation. Django's also whining about `admin_tools.template_loaders.TemplateLoader` even after I add it to `TEMPLATE_LOADERS`:

**urls.py**
````python
urlpatterns = patterns('',
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/',  include(admin.site.urls)),
    ...
)
````

**settings.py**
````python
INSTALLED_APPS = (
    'admin_tools',
    'admin_tools.theming',
    'admin_tools.menu',
    'admin_tools.dashboard',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.contenttypes',
    ...
)

TEMPLATES_LOADERS = (
    "admin_tools.template_loaders.Loader",
)

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.static",
    "django.core.context_processors.request",
)
````

**console**
````bash
$ python manage.py migrate
...

$ python manage.py runserver
Performing system checks...

System check identified some issues:

WARNINGS:
admin_tools: (admin_tools.W001) You must add "admin_tools.template_loaders.TemplateLoader" in your template loaders variable, see: https://django-admin-tools.readthedocs.org/en/latest/configuration.html

System check identified 1 issue (0 silenced).
March 14, 2016 - 19:56:46
Django version 1.7.9, using settings '<redacted>.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
````

**Comment by izimobil** [comment]
You have a typo in tour template loaders variable... s/TEMPLATES_/TEMPLATE_/ . Also, you should put thé default Django loaders in it.

**Comment by botnetbuster** [comment]
Solved my problem. Fixed the variable name and included the Django loaders as @izimobil advised. Thanks!

**Comment by arsenalstriker14** [comment]
Django 1.8 > 
TEMPLATE_LOADERS setting deprecated.
You have to use the TEMPLATES dictionary.
I think you're going to want something like:

settings.py

    TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders':[
                'admin_tools.template_loaders.Loader',
                ('django.template.loaders.cached.Loader', [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

also note – django 1.8 moved from django.core.context_processors to django.template.context_processors

**Comment by izimobil** [comment]
This is [already documented](https://django-admin-tools.readthedocs.org/en/latest/configuration.html#required-settings).

**Comment by arsenalstriker14** [comment]
Only saw the call to the deprecated TEMPLATE_LOADERS variable. Pardon me for trying to help.

**Comment by izimobil** [comment]
Sorry, I didn't meant to be rude :) thanks for your help, if you want to make a pull request on the documentation, you are welcome.

**Comment by arsenalstriker14** [comment]
Perhaps I was a bit touchy. Apologies.

**Comment by Chiheb-Nexus** [comment]
Thanks @arsenalstriker14  your config worked within django 2

**Comment by mnsrknp** [comment]
Worked for in django 2.2
`'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
            'loaders': [
                'admin_tools.template_loaders.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },`

**Comment by Smit-mandavia** [comment]
Thanks @arsenalstriker14 your config worked within django 3.0 
I was stuck actually.

**Comment by Aqib8860** [comment]
> Django 1.8 >
> TEMPLATE_LOADERS setting deprecated.
> You have to use the TEMPLATES dictionary.
> I think you're going to want something like:
> 
> settings.py
> 
> ```
> TEMPLATES = [
> {
>     'BACKEND': 'django.template.backends.django.DjangoTemplates',
>     'DIRS': [os.path.join(BASE_DIR, "templates")],
>     'OPTIONS': {
>         'context_processors': [
>             'django.template.context_processors.debug',
>             'django.template.context_processors.request',
>             'django.contrib.auth.context_processors.auth',
>             'django.contrib.messages.context_processors.messages',
>         ],
>         'loaders':[
>             'admin_tools.template_loaders.Loader',
>             ('django.template.loaders.cached.Loader', [
>             'django.template.loaders.filesystem.Loader',
>             'django.template.loaders.app_directories.Loader',
>             ]),
>         ],
>     },
> },
> ```
> 
> ]
> 
> also note – django 1.8 moved from django.core.context_processors to django.template.context_processors

Really Helpful..................Thnx Its solve my issues!
