### ISSUE TITLE
app_dirs must not be set when loaders is defined

### ISSUE THREAD

**Issue by benzolius** [django-admin-tools/django-admin-tools#43]
I'm trying to use django-admin-tools as instructed here:

http://django-admin-tools.readthedocs.org/en/latest/configuration.html

I get this:

  File "/home/age/prj/django-admin/venv/lib/python3.4/site-packages/django/template/engine.py", line 44, in __init__
    "app_dirs must not be set when loaders is defined.")
django.core.exceptions.ImproperlyConfigured: app_dirs must not be set when loaders is defined.

When I remove APP_DIRS = True I get:

"TemplateDoesNotExist at /admin/
admin/index.html
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/
Django Version:	1.9.1
Exception Type:	TemplateDoesNotExist
Exception Value:	admin/index.html
..."

My environment:
Kubuntu Linux 14.04
Python 3.4
Django 1.9.1

**Comment by izimobil** [comment]
This is not a django-admin-tools issue, you probably didn't set the django templates loaders setting correctly. 

Make sure you have `django.template.loaders.filesystem.Loader` and `django.template.loaders.app_directories.Loader` in your template loaders.

**Comment by benzolius** [comment]
Thanks for explanation.

**Comment by asor1** [comment]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders' : (
                'admin_tools.template_loaders.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ),
        },
    },
]
I did everything as you advised the man above, but still gives indintichnuyu error. Virtualenv use, just using Django 1.10 and the latest release of your Django-admin Tools

**Comment by KINGH242** [comment]
In Django 1.10 you cannot have "APP_DIRS" setting simultaneously with 'loaders' option set in "Templates".

The solution, in my case at least, was to remove 'APP_DIRS':True, but make sure include 'django.template.loaders.app_directories.Loader' in the 'loaders' option under 'Templates'.  These two settings are one in the same.
For more info on Djanog Template Loaders see [here](https://docs.djangoproject.com/en/1.10/ref/templates/api/#django.template.loaders.app_directories.Loader)

**Comment by lggwettmann** [comment]
This would be useful in the documentation. It's very messy in the configuration section and this clarified it for me a lot. Thanks for this post.
