### ISSUE TITLE
404 is raise

### ISSUE THREAD

**Issue by wangshunping** [django-admin-tools/django-admin-tools#47]
When I modify settings.py and urls.py according to http://django-admin-tools.readthedocs.org/en/latest/quickstart.html and locate url , it was always raising 404 to me.

![image](https://cloud.githubusercontent.com/assets/10842398/14244616/a06d15d0-fa8e-11e5-9df8-7af932c6086e.png)

![image](https://cloud.githubusercontent.com/assets/10842398/14244619/a5ee59ec-fa8e-11e5-947e-3ae873a2e086.png)

Do you have any idea about this problem?

THX

**Comment by izimobil** [comment]
Please make sure your urls configuration is OK. If you want more help you'll have to post more information on your setup.

**Comment by izimobil** [comment]
I'm closing this issue since there is no feedback.

**Comment by garylim-me** [comment]
Hi! I'm getting something very similar to the OP (also followed the quickstart guide). Here's my screenshot:

<img width="922" alt="screenshot 2016-09-08 14 53 14" src="https://cloud.githubusercontent.com/assets/1128448/18368304/3161aba8-75d4-11e6-91e6-ef1531bd512d.png">

and my urls.py:

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # django-admin-tools
    url(r'^admin/', include('admin_tools.urls')),

    # User management
    url(r'^users/', include('omnibadge.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
```

I'm using 0.80 on Django 1.9. Thanks!

**Comment by izimobil** [comment]
Well, you didn't configure your urls as the quickstart guide says. Tou must configure the admin site "normally" and add this to your url conf:
`url(r'^admin_tools/', include('admin_tools.urls'))`
https://django-admin-tools.readthedocs.io/en/latest/configuration.html

**Comment by garylim-me** [comment]
I thought the regex could be defined by the user, but I've made the changes to my urls.py file, and still got the same error. Here's the new screenshot after making the changes:

<img width="910" alt="screenshot 2016-09-08 15 45 42" src="https://cloud.githubusercontent.com/assets/1128448/18369581/814818f8-75db-11e6-866c-95e2adbe5dbb.png">

**Comment by izimobil** [comment]
Sure the regex is customizable, but why do you want to call admin_tools views directly ?
Those views are only used internally by admin tools, they are not intended to be accessed directly, you must point your browser to the **django admin interface** instead (ie. /admin/ or whatever URL path you set for it).

Please redo the steps as explained in the quickstart guide and it will work. See also how to set up the django admin interface here: https://docs.djangoproject.com/en/1.9/ref/contrib/admin/

**Comment by izimobil** [comment]
To be more clear: Django Admin Tools is **not** a replacement app for the django admin, it's just a layer on top of it.

**Comment by garylim-me** [comment]
Oh! Ok I get it now. Thanks for clarifying!! 

Just to close the loop here in case anyone else stumbles on this, here's a snippet of my urls.py (includes both url mappings):

```
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^admin/', admin.site.urls),  # original django admin
    url(r'^admin_tools/', include('admin_tools.urls')),  # django-admin-tools
    ...
```

**Comment by sharp** [comment]
with django2, it's still 404

**Comment by oderofrancis** [comment]
am experiencing the same problem ,i  have tried to debug but nothing has changed

**Comment by StevenMonty** [comment]
I am also experiencing this with Django 3.0.7, I even copied and pasted the settings from the test file and still not working.

**Comment by deveshgoyal** [comment]
For Django 2.2

In settings.py

```
INSTALLED_APPS = [
    'admin_tools',
    'admin_tools.theming',
    'admin_tools.menu',
    'admin_tools.dashboard',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ....
]
```
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': False,  # set this to False
        'OPTIONS': {
            'debug': DEBUG,
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'admin_tools.template_loaders.Loader',
            ],
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```
