### ISSUE TITLE
Correction for Django Warning for Template Loader +

### ISSUE THREAD

**Issue by datamafia** [django-admin-tools/django-admin-tools#57]
The following warning is issued:

```
admin_tools: (admin_tools.W001) You must add "admin_tools.template_loaders.TemplateLoader" in your template loaders variable, see: https://django-admin-tools.readthedocs.org/en/latest/configuration.html
```

When added as instructed:

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [  
		...
        ],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
		...
            ],
            'loaders': [
                'admin_tools.template_loaders.TemplateLoader',
```

the following error is returned:

```
  File "PATH/TO/venv/lib/python2.7/site-packages/django/utils/module_loading.py", line 29, in import_string
    return getattr(module, class_name)
ImportError: Module "django.template.loaders.app_directories" does not define a "TemplateLoader" attribute/class
```

I noticed that ```admin_tools.template_loaders``` has a class named ```Loader``` as seen:

https://github.com/django-admin-tools/django-admin-tools/blob/master/admin_tools/template_loaders.py#L41

More than happy to issue a PR if that helps, wanted to confirm this minor issue or get corrected in the case I missed something. 

Thanks for all the hard work.

**Comment by izimobil** [comment]
Hi,
yes it was a typo in the warning message that has been fixed in master: https://github.com/django-admin-tools/django-admin-tools/blob/master/admin_tools/checks.py#L6
