### ISSUE TITLE
Using MultiTenant - sometimes Admin-Tools dashboard does not show up

### ISSUE THREAD

**Issue by mboisvertUW** [django-admin-tools/django-admin-tools#63]
I have been successfully using Admin-tools for awhile and really like it.  Easy to use and does what I need.  However, recently I changed my app to be multitenant (using django-tenants) and sometimes the dashboard file seems to be ignored.  Oddly enough, what I have found 'fixes' it is making a change to the settings file.  Once I do that and refresh it will work correctly.

Any idea why that would be?  I can't always reproduce the issue - which is my biggest concern.  If I could reproduce it intentionally and know it wouldn't come back I would be okay with the work around but I haven't found the true cause.

**Comment by izimobil** [comment]
Sorry I have no idea, I suspect it could be a threadlocals issue, this kink of bug is really hard to track, you should report a bug in the multitenant tracker instead. Regards.
