### ISSUE TITLE
The error after Django upgrade to 1.10

### ISSUE THREAD

**Issue by dhcn** [django-admin-tools/django-admin-tools#65]
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/admin_tools/urls.py", line 2, in <module>
    from django.conf.urls import patterns, url, include
ImportError: cannot import name patterns

**Comment by dhcn** [comment]
Second Error:
Error during template rendering

In template /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/admin_tools/dashboard/templates/admin/index.html, error at line 0
The format for date objects may not contain time-related format specifiers (found 'H').
1	{% extends "admin:admin/index.html" %}
2	{% load admin_tools_dashboard_tags %}
3	{% block extrastyle %}
4	    {{ block.super }}
5	    {% block dashboard_css %}{% admin_tools_render_dashboard_css %}{% endblock %}
6	{% endblock %}
7	{% block coltype %}{% endblock %}
8	{% block bodyclass %}dashboard{% endblock %}
9	{% block content_title %}{% endblock %}
10	{% block content %}

Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/
Django Version:	1.10
Exception Type:	TypeError
Exception Value:	
The format for date objects may not contain time-related format specifiers (found 'H').
Exception Location:	/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/dateformat.py in format, line 40
Python Executable:	/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python

**Comment by PetrDlouhy** [comment]
This should be fixed by #60. But there is no PyPI release with those last commits. @izimobil can you please make new PyPI version?

**Comment by izimobil** [comment]
@PetrDlouhy are you sure this is fixed by pull request #60 ?

**Comment by PetrDlouhy** [comment]
The original error should be fixed by https://github.com/django-admin-tools/django-admin-tools/pull/60/commits/2bf278d6acc0b87b794ed36173ba46e9566b7ae4

I am not sure about the second error, because I don't get such error in my installation. @dhcn you might need to provide more information about specific settings of your installation.

**Comment by izimobil** [comment]
OK. Thanks, a release is coming soon.

**Comment by izimobil** [comment]
0.8.0 released :)
