### ISSUE TITLE
Logged in user can delete arbitrary bookmarks knowing only id

### ISSUE THREAD

**Issue by rootart** [django-admin-tools/django-admin-tools#69]
Currently, it is possible to delete any bookmark as there is no check if it belongs to the logged in user or not. 
https://github.com/django-admin-tools/django-admin-tools/blob/master/admin_tools/menu/views.py#L82
Do you consider changing this behaviour? 

Thanks.

**Comment by vstoykov** [comment]
Can you provide a pull request?

**Comment by rootart** [comment]
@vstoykov thanks for the answer.  Sure, will prepare one this week.

**Comment by rootart** [comment]
@vstoykov would be great if you have a quick look on https://github.com/django-admin-tools/django-admin-tools/pull/70
