### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by izimobil** [django-admin-tools/django-admin-tools#7]
Releasing a new version is quite urgent as v0.5.2 is *not* compatible with django 1.8 (and has issues with 1.7 as well).

On the top of my head, here are the things that block the release:
- ensure manually that all is working with django 1.7 and 1.8 (unit tests aren't enough)
- update docs ! and emphasize the fact we no longer support django < 1.7
- build a release note (and emphasize... see above)
- release away ;)

Any takers on the tasks above (I have not enough free time to do it right atm... except for the last point ;)) ?

I think we should version this release as 0.6.0 and, hopefully, next release will be a stable one (1.0.0).

**Comment by andybak** [comment]
My time is fairly limited for the next couple of weeks so I'll be limited to contributing where it overlaps with my project requirements.

I've currently using the dashboard successfully with Django 1.7 and I'm fairly sure it works with 1.8 as well. (I have an experimental 1.8 branch for the same project and it seemed ok). Not very scientific or rigorous but it's another datapoint for the 'does it work on 1.8?' discussion.

I'm not using the menu at the moment - and I'm using https://github.com/elky/django-flat-theme - which should be released as part of 1.9 as far as I know.

Could we get some community help? Maybe a small update to the current release that mentions it doesn't work on >=1.7 but "please use the repo version and report any problems"

**Comment by shtalinberg** [comment]
I manually test ( commit 71ad7eb23415a7e9491225cd972b679b6a2874b7 ) in my project
works with:
Django==1.8.2
django-autocomplete-light==2.2.3
django-reversion==1.8.7
.......
as well. Noticed nothing critical.

**Comment by izimobil** [comment]
I finally found some time to close some issues, update the docs and prepare a CHANGELOG, please review it if you can and if you're all OK, I'll release a 0.6.0 tomorrow.

**Comment by andybak** [comment]
Looks good to me. I've added a couple of comments - mostly minor. Although the settings version check might be worth a look.

**Comment by izimobil** [comment]
@andybak can you have fix those issues before tomorrow ? I don't have any free time this afternoon.
Thanks !

**Comment by andybak** [comment]
Done

**Comment by izimobil** [comment]
https://pypi.python.org/pypi/django-admin-tools/0.6.0 :)

**Comment by andybak** [comment]
Well done. Thanks for your hard work!
