### ISSUE TITLE
Is this plug-in compatible with Django 2.0

### ISSUE THREAD

**Issue by RecNes** [django-admin-tools/django-admin-tools#79]
Last commit at May 30, 2017
Django 2 release date is Dec, 2017.

Readme is saying, requires 1.7 or newer. But, according to difference of dates, I'm wondering is "Admin Tools" plug-in is compatible with Django 2?

**Comment by shtalinberg** [comment]
We are use 0.8.1 on new project with Django 2 - working fine

**Comment by RecNes** [comment]
Thank you for the fast response.
