### ISSUE TITLE
App title does not i18n-ed

### ISSUE THREAD

**Issue by miurahr** [django-admin-tools/django-admin-tools#8]
App titles are always to be capfirst-ed app.label.title().

It should be  {% trans app.name %} that priority of name is

1. verbose_name
2. app.title()

The `verbose_name` is initialized as `app.title()` In django appconfig __init__()  when there is no `verbose_name` specified. It is because we can always use `verbose_name` for  template name.

Problem is located here
https://github.com/django-admin-tools/django-admin-tools/blob/e66125a7cd47dedc92362b2a11ea78b8e7cb7cbe/admin_tools/dashboard/modules.py#L447

It always use `app.title()` instead of `verbose_name`

**Comment by frensjan** [comment]
I'd say ```apps.get_app_config(app_label).verbose_name``` would do the trick to get the app title. (where ```apps``` = ```django.apps```).

**Comment by miurahr** [comment]
Thanks but `apps` in the above function is not `django.apps`

following seems working for me

```
diff --git a/admin_tools/dashboard/modules.py b/admin_tools/dashboard/modules.py
index d740376..29598d5 100644
--- a/admin_tools/dashboard/modules.py
+++ b/admin_tools/dashboard/modules.py
@@ -444,7 +444,7 @@ class AppList(DashboardModule, AppListElementMixin):
             app_label = model._meta.app_label
             if app_label not in apps:
                 apps[app_label] = {
-                    'title': capfirst(app_label.title()),
+                    'title': model._meta.verbose_name_plural,
                     'url': self._get_admin_app_list_url(model, context),
                     'models': []
                 }
```

**Comment by miurahr** [comment]
This is also worked

```
diff --git a/admin_tools/dashboard/modules.py b/admin_tools/dashboard/modules.py
index d740376..4592b6d 100644
--- a/admin_tools/dashboard/modules.py
+++ b/admin_tools/dashboard/modules.py
@@ -4,6 +4,7 @@ Module where admin tools dashboard modules classes are defined.
 
 from django.utils.text import capfirst
 from django.core.urlresolvers import reverse
+from django.apps import apps as django_apps
 from django.contrib.contenttypes.models import ContentType
 from django.forms.util import flatatt
 from django.utils.translation import ugettext_lazy as _
@@ -444,7 +445,7 @@ class AppList(DashboardModule, AppListElementMixin):
             app_label = model._meta.app_label
             if app_label not in apps:
                 apps[app_label] = {
-                    'title': capfirst(app_label.title()),
+                    'title': django_apps.get_app_config(app_label).verbose_name,
                     'url': self._get_admin_app_list_url(model, context),
                     'models': []
                 }
```

**Comment by miurahr** [comment]
@frensjan thanks for suggestion, I've pushed PR on your solution.
Here seems to be a couple of lines that can be better using `django_apps` because there are many `_meta`  but it should be as another issue.

**Comment by frensjan** [comment]
sure, seems like the solution I was going for!
