### ISSUE TITLE
This app doesn't work with django-debug-toolbar

### ISSUE THREAD

**Issue by stardust85** [django-admin-tools/django-admin-tools#80]
##django-debug-toolbar is a popular (almost 5000 github stars) app for inspecting what django does inside (especially good for performance optimization of sql queries of ORM). However, if used with your app, the issue similar to https://github.com/bernardopires/django-tenant-schemas/issues/222 appears. 

I applied the fix the related pull request of that issue (https://github.com/Cadasta/cadasta-platform/pull/1803/files) in my project's urls.py and it worked. So it will probably work also in your app.

**Comment by izimobil** [comment]
I don't understand, this is the official way to setup django-debug-toolbar (https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#urlconf) so what's need to be changed here in django-admin-tools ?

I've been using DAT with DDT for years and never had a problem.

Regards.

**Comment by josircg** [comment]
Hi Izimobil, they change their template configuration and now it's not compatible with django-admin-tools anymore.
