### ISSUE TITLE
Support for Django 2 'view'

### ISSUE THREAD

**Issue by fzzylogic** [django-admin-tools/django-admin-tools#84]
Django 2 'view' permission type is not supported, so models are not shown as links and the menu is not populated if a user only has 'view' perms.

**Comment by fzzylogic** [comment]
Submitted [pull request #85](https://github.com/django-admin-tools/django-admin-tools/pull/85/commits)

**Comment by yakky** [comment]
@fzzylogic thanks for your work
Finally 0.9.0 is out: https://pypi.org/project/django-admin-tools/
