### ISSUE TITLE
NoReverseMatch at /admin/

### ISSUE THREAD

**Issue by willgearty** [django-admin-tools/django-admin-tools#89]
I just tried to install and configure this great tool, but I'm running into the following issue.
I would appreciate any guidance. Thanks!

> NoReverseMatch
> Reverse for 'auth_user_changelist' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
> 
> Request Method: GET
> Request URL: http://localhost:8000/admin/
> Django Version: 1.8.19
> Exception Type: NoReverseMatch
> Exception Value: Reverse for 'auth_user_changelist' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
> Exception Location: /home/vagrant/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 495
> Python Executable: /home/vagrant/venv/bin/python
> Python Version: 2.7.3
> Python Path: ['/home/vagrant/devsite/esp',  '/home/vagrant/venv/lib/python2.7',  '/home/vagrant/venv/lib/python2.7/plat-linux2',  '/home/vagrant/venv/lib/python2.7/lib-tk',  '/home/vagrant/venv/lib/python2.7/lib-old',  '/home/vagrant/venv/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-linux2',  '/usr/lib/python2.7/lib-tk',  '/home/vagrant/venv/local/lib/python2.7/site-packages',  '/home/vagrant/venv/lib/python2.7/site-packages']
> Server Time: Sun, 6 Jan 2019 23:35:09 -0500

My templates look like this:

> TEMPLATES = [
>     {
>         'BACKEND': 'django.template.backends.django.DjangoTemplates',
>         'DIRS': [
>             # Filled in by settings.py so it can depend on PROJECT_ROOT
>         ],
>         'OPTIONS': {
>             'context_processors': [
>                 'esp.context_processors.media_url', # remove this one after all branches are transitioned
>                 'esp.context_processors.esp_user',
>                 'esp.context_processors.current_site',
>                 'esp.context_processors.index_backgrounds',
>                 'esp.context_processors.espuserified_request',
>                 'esp.context_processors.preload_images',
>                 'esp.context_processors.email_settings',
>                 'esp.context_processors.program',
>                 'esp.context_processors.schoolyear',
>                 'django.template.context_processors.i18n',
>                 'django.contrib.auth.context_processors.auth',
>                 'django.contrib.messages.context_processors.messages',
>                 'django.template.context_processors.media',
>                 'django.template.context_processors.debug',
>                 'django.template.context_processors.static',
>                 'django.core.context_processors.request',
>             ],
>             'loaders': [
>                 'admin_tools.template_loaders.Loader',
>                 'esp.utils.template.Loader',
>                 ('django.template.loaders.cached.Loader',
>                     (
>                      'django.template.loaders.filesystem.Loader',
>                      'django.template.loaders.app_directories.Loader',
>                     )
>                 ),
>             ]
>         },
>     },
> ]

My installed apps:

> INSTALLED_APPS = (
>     'admin_tools',
>     'admin_tools.theming',
>     'admin_tools.menu',
>     'admin_tools.dashboard',
>     'django.contrib.auth',
>     'django.contrib.contenttypes',
>     'django.contrib.messages',
>     'django.contrib.sessions',
>     'django.contrib.sites',
>     'django.contrib.staticfiles',

And my urls.py:

> urlpatterns += [
>     url(r'^admin_tools/', include('admin_tools.urls')),
>     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
>     url(r'^admin/ajax_qsd/?$', esp.qsd.views.ajax_qsd),
>     url(r'^admin/ajax_qsd_preview/?$', esp.qsd.views.ajax_qsd_preview),
>     url(r'^admin/ajax_autocomplete/?', esp.db.views.ajax_autocomplete),
>     url(r'^grappelli/', include('grappelli.urls')),
>     url(r'^admin/filebrowser/', include(filebrowser_site.urls)),
>     url(r'^admin/', include(admin_site.urls)),
>     url(r'^accounts/login/$', esp.users.views.login_checked),
>     url(r'^(?P<subsection>(learn|teach|program|help|manage|onsite))/?$',RedirectView.as_view(url='/%(subsection)s/index.html', permanent=True)),
> ]

**Comment by willgearty** [comment]
My team is still running into this problem. @izimobil @yakky any thoughts?

**Comment by willgearty** [comment]
Never mind, I finally figured out the problem! We don't use the default django user model, so the dashboard couldn't pull the resolver for it.

**Comment by TheReFTW** [comment]
@willgearty How did y'all resolve this? I'm running into the same issue.

**Comment by willgearty** [comment]
We have our own custom `admin_site` that we use to register models to, so I just needed to edit `admin_tools/utils.py` to return that instead of the default django one in `get_admin_site()`. The modified version is [here](https://github.com/learning-unlimited/django-admin-tools/blob/esp/admin_tools/utils.py), maybe it'll be useful.

**Comment by TheReFTW** [comment]
It did! Thanks so much.
