### ISSUE TITLE
Children of admin_tools.dashboard.modules.ModelList aren't sorted

### ISSUE THREAD

**Issue by frensjan** [django-admin-tools/django-admin-tools#9]
In contrast to the behavior of ```AppList```, the children of ```admin_tools.dashboard.modules.ModelList``` don't seem to get sorted. Adding ```self.children.sort(key=lambda x: x['title'])``` to [init_with_context](https://github.com/django-admin-tools/django-admin-tools/blob/master/admin_tools/dashboard/modules.py#L527) should do the trick.

**Comment by izimobil** [comment]
Can you please send a pull request for this ? Thanks.

**Comment by izimobil** [comment]
Hmm, It's a bit more complicated than this.

ModelList items that are explicit (you specify each model explicitly without wildcards, eg. django.contrib.auth.models.User) should not be sorted but displayed with same order as the developer choice. Alternatively, when you have a model list that contains items with wild cards (eg. django.contrib.auth.*) I agree that the matching models should be sorted alphabetically like it is done in the AppList module.

Hopefully https://github.com/django-admin-tools/django-admin-tools/commit/98704d5da8ffd8651092414004384bda45fdd3b8 fixes this issue.
