### ISSUE TITLE
is a new release planned ?

### ISSUE THREAD

**Issue by BrunoDesthuilliers** [django-admin-tools/django-admin-tools#90]
I see there have been a couple fixes for django >= 1.11 but the version number is still at 0.8.1 so the only way to update is to install from git - which is a huge no-no for production code. Is there any new release planned ?

**Comment by izimobil** [comment]
When pigs fly

**Comment by robertpro** [comment]
@izimobil look at this

![image](https://user-images.githubusercontent.com/8595170/70289697-3680c580-179b-11ea-9d98-7f53ed5000c9.png)

**Comment by bashu** [comment]
@robertpro 

https://youtu.be/0LTgNVwfMAE?t=65

**Comment by yakky** [comment]
@izimobil do you need any help in releasing this? I'm quite familiar with the release process and I can commit some time to make the next release happen
As I already have the commit access I just need proper permissions on pypi

**Comment by izimobil** [comment]
@yakky if you have commit access, go ahead and prepare the new release (readme, changelog, etc.), then I'll publish it to pypi, thanks !.

**Comment by yakky** [comment]
I created `release/0.9.0` to run tests against it if everything is green I'll push commit 8deac260f20f10d47b3a2f8407135997362578fe directly to master and I will tag it 
I marked release as 0.9.0

After this I already have a PR for Django 3.0 support, but I think it's better to release what we have now and ship django 3.0 in (possibly near) future release

**Comment by yakky** [comment]
#98 merged with #101 tagging 0.9.0 release

**Comment by yakky** [comment]
@izimobil 0.9.0 merged on master and tagged
Feel free to release to pypi at any time
I will close related issues (tagged with `0.9.0` milestone) after release on pypi

Thanks all here for your patience!

**Comment by izimobil** [comment]
Finally 0.9.0 is out: https://pypi.org/project/django-admin-tools/
Many thanks to @yakky and all the people who helped !

**Comment by yakky** [comment]
@izimobil thans for the release!
