### ISSUE TITLE
Admin layout broken in Django 2.2

### ISSUE THREAD

**Issue by vdboor** [django-admin-tools/django-admin-tools#92]
In Django 2.2 the admin menu is no longer shown properly.
This happens due to this CSS rule in Django's default styling: `#header { display: flex }`.

I've tried tweaking this, but my flexbox knowledge is limited here, so I hope someone could look into this.

**Comment by mmcardle** [comment]
@vdboor 
I copied this template to my own templates and added the snippet below
https://github.com/django-admin-tools/django-admin-tools/blob/master/admin_tools/menu/templates/admin_tools/menu/css.html

```
<style>
#header {
  display: block;
  padding: 0px;
}
#user-tools {
  margin: 20px;
}
</style>
```
