### ISSUE TITLE
User based query permission 

### ISSUE THREAD

**Issue by prakhar-goel** [django-admin-tools/django-admin-tools#96]
As detailed in this question, https://stackoverflow.com/questions/45320643/django-sql-explorer-user-based-query-access can we authorize different queries based on User or User Groups?

For example, for an organisation, there are 2 groups - workers and managers.
Workers group should only get access to query1 and query2. Managers group has access to all queries.

**Comment by izimobil** [comment]
How is this related to django-admin-tools ?!
