### ISSUE TITLE
ImportError: cannot import name 'render_to_response' Django 3.0 upgrade used pip

### ISSUE THREAD

**Issue by vladpaul09** [django-admin-tools/django-admin-tools#99]
The render_to_response shortcut was deprecated in Django 2.0, and is removed in Django 3.0.

**Comment by vladpaul09** [comment]
i see in git that admin-tools/menu/views.py use render.

**Comment by vladpaul09** [comment]
I resolve it by cloning the project and run python setup.py install. I think the pip module install is linked with old version, must be updated.

**Comment by ddimmich** [comment]
This is fixed in this PR: https://github.com/django-admin-tools/django-admin-tools/pull/98
